apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-secrets-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: flask-secrets:latest
  source:
    type: Git
    git:
      uri: https://github.com/niki2805/ML-Openshift.git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.11-ubi9
        namespace: openshift
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: my-github-webhook-secret
