apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: flask-ci-pipeline-run
spec:
  pipelineRef:
    name: flask-ci-pipeline
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: pipeline-pvc
  params:
    - name: repo-url
      value: https://github.com/niki2805/ML-Openshift.git
    - name: image-url
      value: quay.io/nikitam285-dev/flask-secrets