apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: oc-deploy
spec:
  workspaces:
    - name: source
  steps:
    - name: oc-deploy
      image: registry.redhat.io/openshift4/ose-cli
      script: |
        cd $(workspaces.source.path)
        oc rollout restart deployment/config-app -n your-dev-namespace